---
- hosts: webservers 
  become: True
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
